name: gweiland_flutter_task
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0-48.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  gweiland_common:
   path: ../packages/gweiland_common
  gweiland_localization:
   path: ../packages/gweiland_localization
  gweiland_network:
   path: ../packages/gweiland_network 
  gweiland_assets:
   path: ../packages/gweiland_assets

  cupertino_icons: ^1.0.2
  dimensions_theme: ^0.0.2+1
  go_router: ^6.0.1
  riverpod: ^2.1.3
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  http: ^1.1.0
  flutter_screenutil: ^5.6.0
  dartz: ^0.10.1
  shared_preferences: ^2.0.17
  intl: ^0.18.1
  equatable: ^2.0.5
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
