# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
     - name: checkout
       uses: actions/checkout@v3.0.1
     - name: set up JDK 1.8
       uses: actions/setup-java@8
       with:
         distribution: 'zulu' # See 'Supported distributions' for available options
         java-version: '8'
     - name: Flutter action
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
     - run: flutter --version
     - run: flutter pub get
     - run: flutter test
     - run: flutter build apk
     - run: flutter build appbundle
